version: '3.8'

volumes:
  nginx-shared-txs:
  nginx-shared-cfg:

x-healthcheck-db-template: &pghealthcheck
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 30s
    timeout: 30s
    retries: 3

x-healthcheck-redis-template: &redishealthcheck
  healthcheck:
    test: ["CMD", "redis-cli", "ping"]
    interval: 30s
    timeout: 30s
    retries: 3

services:

  # Common nginx and database
  nginx:
    image: nginx:alpine
    ports:
      - "${REVERSE_PROXY_PORT}:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared-txs:/nginx-txs
      - nginx-shared-cfg:/nginx-cfg
    depends_on:
      - txs-web
      - cfg-web
      - cgw-web

  txs-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/txs-db:/var/lib/postgresql/data
    <<: *pghealthcheck

  cfg-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/cfg-db:/var/lib/postgresql/data
    <<: *pghealthcheck

  # Safe Transaction Service
  txs-redis:
    image: redis:alpine
    <<: *redishealthcheck

  txs-rabbitmq:
    image: rabbitmq:alpine

  txs-web:
    image: safeglobal/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
    depends_on:
      txs-db:
        condition: service_healthy
      txs-redis:
        condition: service_healthy
    working_dir: /app
    volumes:
      - nginx-shared-txs:/nginx
    command: docker/web/run_web.sh

  txs-worker-indexer: &txs-worker
    image: safeglobal/safe-transaction-service:${TXS_VERSION}
    env_file:
      - container_env_files/txs.env
    environment:
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
      - RUN_MIGRATIONS=1
      - WORKER_QUEUES=default,indexing
    depends_on:
      txs-db:
        condition: service_healthy
      txs-redis:
        condition: service_healthy
    command: docker/web/celery/worker/run.sh

  txs-worker-contracts-tokens:
    <<: *txs-worker
    environment:
      - WORKER_QUEUES=contracts,tokens
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
    depends_on:
      txs-db:
        condition: service_healthy
      txs-redis:
        condition: service_healthy

  txs-worker-notifications-webhooks:
    <<: *txs-worker
    environment:
      - WORKER_QUEUES=notifications,webhooks
      - ETHEREUM_NODE_URL=${RPC_NODE_URL}
    depends_on:
      txs-db:
        condition: service_healthy
      txs-redis:
        condition: service_healthy

  txs-scheduler:
    <<: *txs-worker
    depends_on:
      txs-db:
        condition: service_healthy
      txs-redis:
        condition: service_healthy
    command: docker/web/celery/scheduler/run.sh

  # Safe Config Service
  cfg-web:
    image: safeglobal/safe-config-service:${CFG_VERSION}
    tty: true
    volumes:
      - nginx-shared-cfg:/nginx
    env_file:
      - container_env_files/cfg.env
    depends_on:
      cfg-db:
        condition: service_healthy

  # Safe Client Gateway
  cgw-redis:
    image: redis:alpine
    <<: *redishealthcheck

  cgw-web:
    image: safeglobal/safe-client-gateway:${CGW_VERSION}
    env_file:
      - container_env_files/cgw.env
    depends_on:
      cgw-redis:
        condition: service_healthy

  ui:
    image: safeglobal/safe-wallet-web:${UI_VERSION}
    env_file:
      - container_env_files/ui.env
    depends_on:
      - nginx
    ports:
      - "${REVERSE_PROXY_UI_PORT}:3000"
